name: Build Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'AgentVersion'     
        required: true
        default: '2.191.1'
      tag:
        description: 'BuildTag'     
        required: true
        default: 'latest'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        - name: 'Docker login'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - name: 'Docker image build and push'
          run: |
            docker build . --build-arg AGENT_VERSION=${{inputs.version}} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/linux-auzre-agent:{{inputs.version}} 
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.REGISTRY_USERNAME }}/linux-auzre-agent:{{inputs.version}}
